### ISSUE TITLE
two different type of responses in showing using Wiql playground and normal query form postman

### ISSUE THREAD

**Issue by yakkalipavan** [ostreifel/wiql-editor#10]
Hi 

I am facing issue of two different responses using different tools
with **Wiql playgorund** i am able to get the result as table but when 
```
Query : SELECT
        [System.Id],
        [System.WorkItemType],
        [System.Title] FROM workitems 
WHERE [System.AreaPath] = 'Test Agile Project\Winter Sprint 1' 
and  [System.state]='New'
```
**Wiql playgorund Results:**
793	User Story	Winter Sprint 1 user story 7
792	User Story	Winter Sprint 1 user story 6
Found 2 results

with postman using POST url the response is like as below for the same query

**postman Results**

```
{
    "queryType": "flat",
    "queryResultType": "workItem",
    "asOf": "2017-10-26T18:40:00.95Z",
    "columns": [
        {
            "referenceName": "System.Id",
            "name": "ID",
            "url": "https://tfs.XYZ.edu/tfs/ITS%20AppDev/_apis/wit/fields"
        },
        {
            "referenceName": "System.WorkItemType",
            "name": "Work Item Type",
            "url": "https://tfs.XYZ.edu/tfs/ITS%20AppDev/_apis/wit/fields"
        },
        {
            "referenceName": "System.Title",
            "name": "Title",
            "url": "https://tfs.XYZ.edu/tfs/ITS%20AppDev/_apis/wit/fields"
        }
    ],
    "workItems": [
        {
            "id": 792,
            "url": "https://tfs.XYZ.edu/tfs/ITS%20AppDev/_apis/wit/workItems/792"
        },
        {
            "id": 793,
            "url": "https://tfs.XYZ.edu/tfs/ITS%20AppDev/_apis/wit/workItems/793"
        }
    ]
}
```

So I am expecting the column values to display in postman response. Is there any way i can get display the column values instead of just the URLs of workitems

Thanks
Pavan

**Comment by ostreifel** [comment]
Internally the extension is actually making 2 calls. 1 to run the query, 1 to get the [workitem columns](https://www.visualstudio.com/en-us/docs/integrate/api/wit/work-items). This is increasingly important when the query retrieves hundreds or thousands of workitems because the workitems can only be retrieved in batches of 200.

**Comment by yakkalipavan** [comment]
Thanks you very much for the response. So if i understand correctly, first running the query and using this response we are getting the work item columns. I would be so thankful  if you tell me to do the second one (that is to get the work item column **VALUES**)

**Comment by ostreifel** [comment]
Running the query
https://github.com/ostreifel/wiql-editor/blob/master/extension/scripts/wiqlPlayground/playground.ts#L50

Getting the work items for a flat query
https://github.com/ostreifel/wiql-editor/blob/master/extension/scripts/wiqlPlayground/playground.ts#L10

Getting results for tree queries
https://github.com/ostreifel/wiql-editor/blob/master/extension/scripts/wiqlPlayground/playground.ts#L24


There isn't any batching logic because the playground has a hard coded limit of 50 workitems for all queries.
