### ISSUE TITLE
An undefined error occurred while attempting to connect to the server. Status code 0: error.

### ISSUE THREAD

**Issue by tsqn** [ostreifel/wiql-editor#2]
Hi.
When i run query with big result table, i have an error.
In our collection we have are more than 10k work items.

![image4](https://cloud.githubusercontent.com/assets/20081583/22776175/3fd1e258-eee1-11e6-9af2-e13bb8073c68.png)
![image3](https://cloud.githubusercontent.com/assets/20081583/22776176/3ff42098-eee1-11e6-8b02-f4d5d8f924e8.png)

**Comment by ostreifel** [comment]
The error should not be dependent on how many items there are because the playground always uses the top=50 limit.

Can you check the request urls bodies and responses from the network tab?
Specifically ones with urls for the query

https://[server]/[project]/[team]/_apis/wit/wiql?%24top=50
{"query":"SELECT\n        [System.Id]\nFROM workitems\nWHERE\n        [id] < 100000 and\n        [System.TeamProject] = @project\n        ORDER BY id desc\n"}

//Response body here

and the work items in the response
https://[server]/_apis/wit/workItems?ids=999...&fields=System.Id&asOf=2017-02-09T18%3A02%3A24.250Z

Is the extension breaking when it makes a query call or when it attempts to retrieve the work item columns? 
Is there a specific work item that causes the error? 
What other variations of this query cause the error?
-  Does it also happen with  < 2100, < 4000
-  Does it happen with order by id desc/asc
- If this is a specific work item check the ids between 1900 and 2000 - what makes that particular work item different?

**Comment by Kujawadl** [comment]
You may need to reopen this. I also get this error, and it's almost certainly due to too many results.

I get several errors in the javascript console:

```
OPTIONS http://tfs.{Server}.com/tfs/DefaultCollection/_apis/wit/workI….Id%2CSystem.State%2CSystem.WorkItemType&asOf=2017-05-17T13%3A57%3A16.813Z 414 (Request-URI Too Long)
...
AI: UrlTooLong message:"url is too long, it has been truncated to 2048 characters.".
```

I'm attaching the URL it's generating in a text file (it's wayyyy too big to paste here). The bulk of it looks to be thousands and thousands of work item IDs. The URL ends with `/workItems?ids=...`, so I'm guessing this is after the query has returned the results, and now it's trying to fetch information about them to populate the table..?

[url.txt](https://github.com/ostreifel/wiql-editor/files/1007984/url.txt)

**Comment by ostreifel** [comment]
Published

**Comment by ostreifel** [comment]
Please verify that this issue is fixed.

**Comment by Kujawadl** [comment]
Fixed :+1:
